// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/crisyantoparulian/checkout-service/internal/app/usecase/checkout (interfaces: CheckoutUsecase)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/usecase/checkout/mocks/usecase.go -package=mocks github.com/crisyantoparulian/checkout-service/internal/app/usecase/checkout CheckoutUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	checkout "github.com/crisyantoparulian/checkout-service/internal/app/usecase/checkout"
	gomock "go.uber.org/mock/gomock"
)

// MockCheckoutUsecase is a mock of CheckoutUsecase interface.
type MockCheckoutUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCheckoutUsecaseMockRecorder
	isgomock struct{}
}

// MockCheckoutUsecaseMockRecorder is the mock recorder for MockCheckoutUsecase.
type MockCheckoutUsecaseMockRecorder struct {
	mock *MockCheckoutUsecase
}

// NewMockCheckoutUsecase creates a new mock instance.
func NewMockCheckoutUsecase(ctrl *gomock.Controller) *MockCheckoutUsecase {
	mock := &MockCheckoutUsecase{ctrl: ctrl}
	mock.recorder = &MockCheckoutUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckoutUsecase) EXPECT() *MockCheckoutUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCheckoutUsecase) Create(ctx context.Context, req checkout.CreateCheckoutRequest) (checkout.CheckoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(checkout.CheckoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCheckoutUsecaseMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCheckoutUsecase)(nil).Create), ctx, req)
}

// GetDetail mocks base method.
func (m *MockCheckoutUsecase) GetDetail(ctx context.Context, checkoutID string) (checkout.CheckoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetail", ctx, checkoutID)
	ret0, _ := ret[0].(checkout.CheckoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetail indicates an expected call of GetDetail.
func (mr *MockCheckoutUsecaseMockRecorder) GetDetail(ctx, checkoutID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetail", reflect.TypeOf((*MockCheckoutUsecase)(nil).GetDetail), ctx, checkoutID)
}
