package constants

const (
	CODE_DUPLICATE_USERNAME_OR_EMAIL = "0001"
	CODE_RECORD_NOT_FOUND            = "0002"
	CODE_CREATE_ERROR                = "0003"
	CODE_UPDATE_ERROR                = "0004"
	CODE_DELETE_ERROR                = "0005"
	CODE_PRODUCT_NOT_FOUND           = "PRODUCT_NOT_FOUND"
	CODE_CHECKOUT_NOT_FOUND          = "CHECKOUT_NOT_FOUND"
	CODE_INSUFFICIENT_STOCK          = "INSUFFICIENT_STOCK"
	CODE_INVALID_QUANTITY            = "INVALID_QUANTITY"
	CODE_INVALID_PROMOTION_RULE      = "INVALID_PROMOTION_RULE"
	CODE_INVALID_REQUEST             = "9998"
	CODE_GENERAL_ERROR               = "9999"
)
