// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/crisyantoparulian/checkout-service/internal/app/usecase/health_check (interfaces: HealthCheckUsecase)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/usecase/health_check/mocks/usecase.go -package=mocks github.com/crisyantoparulian/checkout-service/internal/app/usecase/health_check HealthCheckUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	health_check "github.com/crisyantoparulian/checkout-service/internal/app/usecase/health_check"
	gomock "go.uber.org/mock/gomock"
)

// MockHealthCheckUsecase is a mock of HealthCheckUsecase interface.
type MockHealthCheckUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckUsecaseMockRecorder
	isgomock struct{}
}

// MockHealthCheckUsecaseMockRecorder is the mock recorder for MockHealthCheckUsecase.
type MockHealthCheckUsecaseMockRecorder struct {
	mock *MockHealthCheckUsecase
}

// NewMockHealthCheckUsecase creates a new mock instance.
func NewMockHealthCheckUsecase(ctrl *gomock.Controller) *MockHealthCheckUsecase {
	mock := &MockHealthCheckUsecase{ctrl: ctrl}
	mock.recorder = &MockHealthCheckUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthCheckUsecase) EXPECT() *MockHealthCheckUsecaseMockRecorder {
	return m.recorder
}

// HealthCheck mocks base method.
func (m *MockHealthCheckUsecase) HealthCheck(ctx context.Context) (health_check.StatusCheck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(health_check.StatusCheck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockHealthCheckUsecaseMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockHealthCheckUsecase)(nil).HealthCheck), ctx)
}
