// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/crisyantoparulian/checkout-service/internal/app/repository (interfaces: Checkout)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/repository/mocks/checkout.go -package=mocks github.com/crisyantoparulian/checkout-service/internal/app/repository Checkout
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/crisyantoparulian/checkout-service/internal/app/entity"
	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockCheckout is a mock of Checkout interface.
type MockCheckout struct {
	ctrl     *gomock.Controller
	recorder *MockCheckoutMockRecorder
	isgomock struct{}
}

// MockCheckoutMockRecorder is the mock recorder for MockCheckout.
type MockCheckoutMockRecorder struct {
	mock *MockCheckout
}

// NewMockCheckout creates a new mock instance.
func NewMockCheckout(ctrl *gomock.Controller) *MockCheckout {
	mock := &MockCheckout{ctrl: ctrl}
	mock.recorder = &MockCheckoutMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckout) EXPECT() *MockCheckoutMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCheckout) Create(ctx context.Context, tx *sqlx.Tx, checkout *entity.Checkout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, checkout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCheckoutMockRecorder) Create(ctx, tx, checkout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCheckout)(nil).Create), ctx, tx, checkout)
}

// CreateItem mocks base method.
func (m *MockCheckout) CreateItem(ctx context.Context, tx *sqlx.Tx, item *entity.CheckoutItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, tx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockCheckoutMockRecorder) CreateItem(ctx, tx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockCheckout)(nil).CreateItem), ctx, tx, item)
}

// CreatePromotion mocks base method.
func (m *MockCheckout) CreatePromotion(ctx context.Context, tx *sqlx.Tx, promotion *entity.CheckoutPromotion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePromotion", ctx, tx, promotion)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePromotion indicates an expected call of CreatePromotion.
func (mr *MockCheckoutMockRecorder) CreatePromotion(ctx, tx, promotion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePromotion", reflect.TypeOf((*MockCheckout)(nil).CreatePromotion), ctx, tx, promotion)
}

// GetByUUID mocks base method.
func (m *MockCheckout) GetByUUID(ctx context.Context, checkoutUUID uuid.UUID) (entity.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", ctx, checkoutUUID)
	ret0, _ := ret[0].(entity.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockCheckoutMockRecorder) GetByUUID(ctx, checkoutUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockCheckout)(nil).GetByUUID), ctx, checkoutUUID)
}

// GetItems mocks base method.
func (m *MockCheckout) GetItems(ctx context.Context, checkoutUUID uuid.UUID) ([]entity.CheckoutItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, checkoutUUID)
	ret0, _ := ret[0].([]entity.CheckoutItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockCheckoutMockRecorder) GetItems(ctx, checkoutUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockCheckout)(nil).GetItems), ctx, checkoutUUID)
}

// GetPromotions mocks base method.
func (m *MockCheckout) GetPromotions(ctx context.Context, checkoutUUID uuid.UUID) ([]entity.CheckoutPromotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromotions", ctx, checkoutUUID)
	ret0, _ := ret[0].([]entity.CheckoutPromotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromotions indicates an expected call of GetPromotions.
func (mr *MockCheckoutMockRecorder) GetPromotions(ctx, checkoutUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromotions", reflect.TypeOf((*MockCheckout)(nil).GetPromotions), ctx, checkoutUUID)
}
