// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/crisyantoparulian/checkout-service/internal/app/repository (interfaces: Inventory)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/repository/mocks/inventory.go -package=mocks github.com/crisyantoparulian/checkout-service/internal/app/repository Inventory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/crisyantoparulian/checkout-service/internal/app/entity"
	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockInventory is a mock of Inventory interface.
type MockInventory struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryMockRecorder
	isgomock struct{}
}

// MockInventoryMockRecorder is the mock recorder for MockInventory.
type MockInventoryMockRecorder struct {
	mock *MockInventory
}

// NewMockInventory creates a new mock instance.
func NewMockInventory(ctrl *gomock.Controller) *MockInventory {
	mock := &MockInventory{ctrl: ctrl}
	mock.recorder = &MockInventoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventory) EXPECT() *MockInventoryMockRecorder {
	return m.recorder
}

// CreateMovement mocks base method.
func (m *MockInventory) CreateMovement(ctx context.Context, tx *sqlx.Tx, movement *entity.InventoryMovement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMovement", ctx, tx, movement)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMovement indicates an expected call of CreateMovement.
func (mr *MockInventoryMockRecorder) CreateMovement(ctx, tx, movement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMovement", reflect.TypeOf((*MockInventory)(nil).CreateMovement), ctx, tx, movement)
}
