// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/crisyantoparulian/checkout-service/internal/app/repository (interfaces: Product)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/repository/mocks/product.go -package=mocks github.com/crisyantoparulian/checkout-service/internal/app/repository Product
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/crisyantoparulian/checkout-service/internal/app/entity"
	repository "github.com/crisyantoparulian/checkout-service/internal/app/repository"
	uuid "github.com/google/uuid"
	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockProduct is a mock of Product interface.
type MockProduct struct {
	ctrl     *gomock.Controller
	recorder *MockProductMockRecorder
	isgomock struct{}
}

// MockProductMockRecorder is the mock recorder for MockProduct.
type MockProductMockRecorder struct {
	mock *MockProduct
}

// NewMockProduct creates a new mock instance.
func NewMockProduct(ctrl *gomock.Controller) *MockProduct {
	mock := &MockProduct{ctrl: ctrl}
	mock.recorder = &MockProductMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProduct) EXPECT() *MockProductMockRecorder {
	return m.recorder
}

// CountTotal mocks base method.
func (m *MockProduct) CountTotal(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotal", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotal indicates an expected call of CountTotal.
func (mr *MockProductMockRecorder) CountTotal(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotal", reflect.TypeOf((*MockProduct)(nil).CountTotal), ctx)
}

// DeductStock mocks base method.
func (m *MockProduct) DeductStock(ctx context.Context, tx *sqlx.Tx, productUUID uuid.UUID, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeductStock", ctx, tx, productUUID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeductStock indicates an expected call of DeductStock.
func (mr *MockProductMockRecorder) DeductStock(ctx, tx, productUUID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductStock", reflect.TypeOf((*MockProduct)(nil).DeductStock), ctx, tx, productUUID, quantity)
}

// GetAll mocks base method.
func (m *MockProduct) GetAll(ctx context.Context, filter repository.ProductFilter) ([]entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, filter)
	ret0, _ := ret[0].([]entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockProductMockRecorder) GetAll(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockProduct)(nil).GetAll), ctx, filter)
}

// GetByUUIDs mocks base method.
func (m *MockProduct) GetByUUIDs(ctx context.Context, uuids []uuid.UUID) ([]entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUIDs", ctx, uuids)
	ret0, _ := ret[0].([]entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUIDs indicates an expected call of GetByUUIDs.
func (mr *MockProductMockRecorder) GetByUUIDs(ctx, uuids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUIDs", reflect.TypeOf((*MockProduct)(nil).GetByUUIDs), ctx, uuids)
}

// GetByUUIDsForUpdate mocks base method.
func (m *MockProduct) GetByUUIDsForUpdate(ctx context.Context, tx *sqlx.Tx, uuids []uuid.UUID) ([]entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUIDsForUpdate", ctx, tx, uuids)
	ret0, _ := ret[0].([]entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUIDsForUpdate indicates an expected call of GetByUUIDsForUpdate.
func (mr *MockProductMockRecorder) GetByUUIDsForUpdate(ctx, tx, uuids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUIDsForUpdate", reflect.TypeOf((*MockProduct)(nil).GetByUUIDsForUpdate), ctx, tx, uuids)
}
