// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/crisyantoparulian/checkout-service/internal/app/repository (interfaces: Promotion)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/repository/mocks/promotion.go -package=mocks github.com/crisyantoparulian/checkout-service/internal/app/repository Promotion
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/crisyantoparulian/checkout-service/internal/app/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPromotion is a mock of Promotion interface.
type MockPromotion struct {
	ctrl     *gomock.Controller
	recorder *MockPromotionMockRecorder
	isgomock struct{}
}

// MockPromotionMockRecorder is the mock recorder for MockPromotion.
type MockPromotionMockRecorder struct {
	mock *MockPromotion
}

// NewMockPromotion creates a new mock instance.
func NewMockPromotion(ctrl *gomock.Controller) *MockPromotion {
	mock := &MockPromotion{ctrl: ctrl}
	mock.recorder = &MockPromotionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromotion) EXPECT() *MockPromotionMockRecorder {
	return m.recorder
}

// GetActiveRulesByTargetProductUUIDs mocks base method.
func (m *MockPromotion) GetActiveRulesByTargetProductUUIDs(ctx context.Context, productUUIDs []uuid.UUID) ([]entity.PromotionRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveRulesByTargetProductUUIDs", ctx, productUUIDs)
	ret0, _ := ret[0].([]entity.PromotionRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveRulesByTargetProductUUIDs indicates an expected call of GetActiveRulesByTargetProductUUIDs.
func (mr *MockPromotionMockRecorder) GetActiveRulesByTargetProductUUIDs(ctx, productUUIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveRulesByTargetProductUUIDs", reflect.TypeOf((*MockPromotion)(nil).GetActiveRulesByTargetProductUUIDs), ctx, productUUIDs)
}
